server {
    listen 80;
    server_name _;

    location = / {
        return 302 /demo/fms/;
    }

    location = /demo/fms {
        return 301 /demo/fms/;
    }

    location = /demo/fms/api/upload {
        proxy_pass https://yz1zrecbsj.execute-api.ap-southeast-1.amazonaws.com/dev/RnD/webapp/file/upload;
        proxy_http_version 1.1;
        proxy_ssl_server_name on;
        proxy_set_header Host yz1zrecbsj.execute-api.ap-southeast-1.amazonaws.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /demo/fms/api/files {
        proxy_pass https://yz1zrecbsj.execute-api.ap-southeast-1.amazonaws.com/dev/RnD/webapp/file/list;
        proxy_http_version 1.1;
        proxy_ssl_server_name on;
        proxy_set_header Host yz1zrecbsj.execute-api.ap-southeast-1.amazonaws.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /demo/fms/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /demo/fms/index.html;
    }
}
